### ISSUE TITLE
Package qfilt doesn't pass on travis 

### ISSUE THREAD

**Issue by JesperBrink** [Hogfeldt/bioconda_recipe_gen#80]
Right now the package qfilt doesn't pass our test on travis (https://travis-ci.org/Hogfeldt/bioconda_recipe_gen/jobs/583010879). The problem is that it works, when you build qfilt locally with our program. (it creates the correct recipe and passes the sanity check).

**Comment by Hogfeldt** [comment]
I just tried to run build qfilt locally too and had a successful build. Then i took a look at the Travis output that you linked to. The line of interest seem to be this: 
```
06:11:22 BIOCONDA INFO (ERR) subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/travis/miniconda3/envs/test/conda-bld/qfilt2_1568095774612/work/conda_build.sh']' returned non-zero exit status 2.
```
It says that the bash shell script exited with status 2. I did a quick search and found this:
```
2 | Misuse of shell builtins (according to Bash documentation) | empty_function() {} | Missing keyword or command, or permission problem (and diff return code on a failed binary file comparison).
```
source: http://www.tldp.org/LDP/abs/html/exitcodes.html
I'm currently not sure what to make of this. Maybe it could be related to permissions since we do not totally control permissions on Travis.

**Comment by Hogfeldt** [comment]
CMake also comes with the warning:
```
06:11:20 BIOCONDA INFO (ERR) CMake Error at cmake_install.cmake:47 (file):

06:11:20 BIOCONDA INFO (ERR)   file INSTALL cannot copy file

06:11:20 BIOCONDA INFO (ERR)   "/home/travis/miniconda3/envs/test/conda-bld/qfilt2_1568095774612/work/build/qfilt"

06:11:20 BIOCONDA INFO (ERR)   to "/usr/local/bin/qfilt".
```
I guess this is the problem which throws and error when `make install` runs. My guess is that this is a permission problem.

**Comment by JesperBrink** [comment]
After triggering another build in travis, qfilt builds. We don't have the exact reason for this, since there have been multiple PR since the this issue started.
